CREATE DATABASE ART_DB;
USE ART_DB;


CREATE TABLE ARTIST (
    ARTIST_ID VARCHAR(5) PRIMARY KEY,
    ARTIST_NAME VARCHAR(30) NOT NULL,
    ARTIST_SURNAME VARCHAR(16) NOT NULL
);
GO

INSERT INTO ARTIST
(ARTIST_ID, ARTIST_NAME, ARTIST_SURNAME)
VALUES
('A001', 'Pablo', 'Picasso'),
('A002', 'Vincent', 'van Gogh'),
('A003', 'Claude', 'Monet'),
('A004', 'Frida', 'Kahlo'),
('A005', 'Salvador', 'Dali');
GO

ALTER TABLE ARTIST
ADD ADDRESS VARCHAR(100),
    CONTACT VARCHAR(20);
GO

UPDATE ARTIST
SET ADDRESS = '15 Art Street, Madrid',
    CONTACT = '0712345678'
WHERE ARTIST_ID = 'A001';

UPDATE ARTIST
SET ADDRESS = '24 Museum Road, Amsterdam',
    CONTACT = '0723456789'
WHERE ARTIST_ID = 'A002';

UPDATE ARTIST
SET ADDRESS = '31 Garden Avenue, Paris',
    CONTACT = '0734567890'
WHERE ARTIST_ID = 'A003';

UPDATE ARTIST
SET ADDRESS = '42 Gallery Road, Mexico City',
    CONTACT = '0745678901'
WHERE ARTIST_ID = 'A004';

UPDATE ARTIST
SET ADDRESS = '56 Art Avenue, Barcelona',
    CONTACT = '0756789012'
WHERE ARTIST_ID = 'A005';
GO

CREATE TABLE GENRE (
    GENRE_ID VARCHAR(5) PRIMARY KEY,
    GENRE_DESCRIPTION VARCHAR(100) NOT NULL
);
GO

INSERT INTO GENRE
(GENRE_ID, GENRE_DESCRIPTION)
VALUES
('G001', 'Modern Art'),
('G002', 'Impressionism'),
('G003', 'Surrealism');
GO

CREATE TABLE ARTWORK (
    ARTWORK_ID VARCHAR(5) PRIMARY KEY,
    ARTWORK_TITLE VARCHAR(50) NOT NULL,
    GENRE_ID VARCHAR(5) NOT NULL,
    ARTIST_ID VARCHAR(5) NOT NULL,
    CONSTRAINT FK_ARTWORK_GENRE
        FOREIGN KEY (GENRE_ID)
        REFERENCES GENRE(GENRE_ID),
    CONSTRAINT FK_ARTWORK_ARTIST
        FOREIGN KEY (ARTIST_ID)
        REFERENCES ARTIST(ARTIST_ID)
);
GO

INSERT INTO ARTWORK
(ARTWORK_ID, ARTWORK_TITLE, GENRE_ID, ARTIST_ID)
VALUES
('AW001', 'Guernica', 'G001', 'A001'),
('AW002', 'Les Demoiselles', 'G001', 'A001'),
('AW003', 'Old Guitarist', 'G001', 'A001'),
('AW004', 'Starry Night', 'G002', 'A002'),
('AW005', 'Sunflowers', 'G002', 'A002'),
('AW006', 'The Bedroom', 'G002', 'A002'),
('AW007', 'Irises', 'G002', 'A002'),
('AW008', 'Water Lilies', 'G002', 'A003'),
('AW009', 'Impression Sunrise', 'G002', 'A003'),
('AW010', 'Woman with Parasol', 'G002', 'A003'),
('AW011', 'Poppy Field', 'G002', 'A003'),
('AW012', 'Self Portrait', 'G001', 'A004'),
('AW013', 'The Two Fridas', 'G001', 'A004'),
('AW014', 'Viva la Vida', 'G001', 'A004'),
('AW015', 'Broken Column', 'G003', 'A004'),
('AW016', 'Persistence Memory', 'G003', 'A005'),
('AW017', 'The Elephants', 'G003', 'A005'),
('AW018', 'Metamorphosis', 'G003', 'A005'),
('AW019', 'Burning Giraffe', 'G003', 'A005'),
('AW020', 'Dream of Bee', 'G003', 'A005');
GO

CREATE TABLE EXHIBITION (
    EXHIBITION_ID VARCHAR(5) PRIMARY KEY,
    EXHIBITION_DESCRIPTION VARCHAR(100) NOT NULL
);
GO

INSERT INTO EXHIBITION
(EXHIBITION_ID, EXHIBITION_DESCRIPTION)
VALUES
('E001', 'Modern Masters Exhibition'),
('E002', 'European Art Exhibition'),
('E003', 'Famous Paintings Exhibition'),
('E004', '20th Century Art'),
('E005', 'Impressionist Collection'),
('E006', 'Surrealist Art Exhibition'),
('E007', 'International Art Festival'),
('E008', 'Classic Art Collection'),
('E009', 'Masters of Modern Art'),
('E010', 'European Masters'),
('E011', 'Art Through the Ages'),
('E012', 'World Famous Artists'),
('E013', 'Summer Art Exhibition'),
('E014', 'Contemporary Art Show'),
('E015', 'Museum Grand Exhibition');
GO

CREATE TABLE ENTRY (
    ENTRY_ID VARCHAR(5) PRIMARY KEY,
    ARTWORK_ID VARCHAR(5) NOT NULL,
    EXHIBITION_ID VARCHAR(5) NOT NULL,
    CONSTRAINT FK_ENTRY_ARTWORK
        FOREIGN KEY (ARTWORK_ID)
        REFERENCES ARTWORK(ARTWORK_ID),
    CONSTRAINT FK_ENTRY_EXHIBITION
        FOREIGN KEY (EXHIBITION_ID)
        REFERENCES EXHIBITION(EXHIBITION_ID)
);
GO

INSERT INTO ENTRY
(ENTRY_ID, ARTWORK_ID, EXHIBITION_ID)
VALUES
('EN001', 'AW001', 'E001'),
('EN002', 'AW001', 'E004'),
('EN003', 'AW001', 'E015'),
('EN004', 'AW002', 'E001'),
('EN005', 'AW002', 'E009'),
('EN006', 'AW003', 'E003'),
('EN007', 'AW003', 'E008'),
('EN008', 'AW004', 'E002'),
('EN009', 'AW004', 'E005'),
('EN010', 'AW005', 'E005'),
('EN011', 'AW005', 'E010'),
('EN012', 'AW006', 'E002'),
('EN013', 'AW007', 'E007'),
('EN014', 'AW008', 'E005'),
('EN015', 'AW008', 'E013'),
('EN016', 'AW009', 'E005'),
('EN017', 'AW010', 'E010'),
('EN018', 'AW011', 'E013'),
('EN019', 'AW012', 'E004'),
('EN020', 'AW013', 'E006'),
('EN021', 'AW013', 'E014'),
('EN022', 'AW014', 'E011'),
('EN023', 'AW015', 'E006'),
('EN024', 'AW016', 'E006'),
('EN025', 'AW016', 'E015'),
('EN026', 'AW017', 'E012'),
('EN027', 'AW018', 'E014'),
('EN028', 'AW019', 'E006'),
('EN029', 'AW020', 'E015');
GO

DELETE FROM ENTRY
WHERE ENTRY_ID = 'EN029';
GO

INSERT INTO ENTRY
(ENTRY_ID, ARTWORK_ID, EXHIBITION_ID)
VALUES
('EN029', 'AW020', 'E015');
GO

SELECT 'ARTIST' AS TABLE_NAME;
SELECT * FROM ARTIST;
GO

SELECT 'GENRE' AS TABLE_NAME;
SELECT * FROM GENRE;
GO

SELECT 'ARTWORK' AS TABLE_NAME;
SELECT * FROM ARTWORK;
GO

SELECT 'EXHIBITION ' AS TABLE_NAME;
SELECT * FROM EXHIBITION;
GO

SELECT 'ENTRY' AS TABLE_NAME;
SELECT * FROM ENTRY;
GO

SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_NAME;
GO

SELECT 'ARTWORK LIST' AS REPORT_NAME;

SELECT
    ARTWORK_ID,
    ARTWORK_TITLE,
    GENRE_ID,
    ARTIST_ID
FROM ARTWORK
WHERE ARTWORK_ID IN
('AW001', 'AW004', 'AW008', 'AW013', 'AW016');
GO

SELECT 'GROUP BY REPORT' AS REPORT_NAME;

SELECT
    GENRE_ID,
    COUNT(ARTWORK_ID) AS TOTAL_ARTWORKS
FROM ARTWORK
GROUP BY GENRE_ID;
GO

SELECT 'HAVING REPORT' AS REPORT_NAME;

SELECT
    ARTIST_ID,
    COUNT(ARTWORK_ID) AS TOTAL_ARTWORKS
FROM ARTWORK
GROUP BY ARTIST_ID
HAVING COUNT(ARTWORK_ID) >= 4;
GO



SELECT
    ARTWORK_ID,
    COUNT(EXHIBITION_ID) AS NUMBER_OF_EXHIBITIONS
FROM ENTRY
GROUP BY ARTWORK_ID
HAVING COUNT(EXHIBITION_ID) > 1;
GO



SELECT
    A.ARTIST_ID,
    A.ARTIST_NAME,
    A.ARTIST_SURNAME,
    W.ARTWORK_ID,
    W.ARTWORK_TITLE,
    G.GENRE_DESCRIPTION
FROM ARTIST AS A
INNER JOIN ARTWORK AS W
    ON A.ARTIST_ID = W.ARTIST_ID
INNER JOIN GENRE AS G
    ON W.GENRE_ID = G.GENRE_ID
ORDER BY A.ARTIST_ID, W.ARTWORK_ID;
GO



SELECT
    W.ARTWORK_ID,
    W.ARTWORK_TITLE,
    E.EXHIBITION_ID,
    E.EXHIBITION_DESCRIPTION
FROM ARTWORK AS W
INNER JOIN ENTRY AS EN
    ON W.ARTWORK_ID = EN.ARTWORK_ID
INNER JOIN EXHIBITION AS E
    ON EN.EXHIBITION_ID = E.EXHIBITION_ID
ORDER BY W.ARTWORK_ID, E.EXHIBITION_ID;
GO

SELECT 'FINAL RECORD COUNTS' AS REPORT_NAME;

SELECT
    (SELECT COUNT(*) FROM ARTIST) AS ARTIST_RECORDS,
    (SELECT COUNT(*) FROM GENRE) AS GENRE_RECORDS,
    (SELECT COUNT(*) FROM ARTWORK) AS ARTWORK_RECORDS,
    (SELECT COUNT(*) FROM EXHIBITION) AS EXHIBITION_RECORDS,
    (SELECT COUNT(*) FROM ENTRY) AS ENTRY_RECORDS;
GO

SELECT'ART_DB REPORT' AS ART_DB
 SELECT * FROM ARTIST;
 SELECT * FROM GENRE;
 SELECT * FROM ARTWORK;
 SELECT * FROM ENTRY;
 SELECT * From EXHIBITION;